Write-Host "Begin deleting"
Remove-Item "fuchsia.aux"
Remove-Item "fuchsia.bbl"
Remove-Item "fuchsia.bcf"
Remove-Item "fuchsia.blg"
Remove-Item "fuchsia.log"
Remove-Item "fuchsia.out"
Remove-Item "fuchsia.synctex.gz"
Remove-Item "fuchsia.toc"
Remove-Item "fuchsia.docx"
Write-Host "Deleting finished"